import type { Metadata } from "next";
import { Montserrat, Cormorant } from "next/font/google";
import Navbar from "./components/Navbar";
import "./globals.css";
import Footer from "./components/Footer";
import { NavigationProvider } from "./providers/NavigationContext";
import { ModalProvider } from "@/app/components/ui/animated-modal";
import AdminAuthKey from "./components/AdminAuthKey";
import { ToastProvider } from "./components/provider/ToastContext";

const montserrat = Montserrat({
  subsets: ["latin"],
});

const cormorant = Cormorant({
  weight: ["400", "600", "700"],
  variable: "--font-cormorant",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Arcadia - Sustainability Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`relative ${montserrat.className} ${cormorant.variable}`}
      >
        <ToastProvider>
          <NavigationProvider>
            <Navbar />
            <ModalProvider>
              <AdminAuthKey />
              {children}
            </ModalProvider>
            <Footer />
          </NavigationProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
